[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "CertiFried"
name = "TechtonicaFramework"
versionNumber = "1.2.0"
description = "Core framework mod providing shared systems for health, damage, narrative, equipment, and environment mechanics for other CertiFried mods."
websiteUrl = "https://github.com/xXDeath420Xx/TTMod-TechtonicaFramework"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Equinox-EquinoxsModUtils = "6.1.3"
Equinox-EMUAdditions = "2.0.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Debug/net472/TechtonicaFramework.dll"
target = "/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["techtonica"]
